version: '3'

services:
  landscaper:
    image: onedata/landscaper:v2.8.0-2
    entrypoint: /entrypoint.sh
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ${kube_config}:/root/.kube/config:ro

# Needed to work in Cyfronet
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400