version: '3'

services:
  landscaper:
    image: groundnuty/landscaper:1.0.6-rc.1-kubectl
    entrypoint: /entrypoint.sh
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ${kube_config}:/root/.kube/config:ro
      - ../landscapes:/landscapes:ro
    environment:
      namespace: "$namespace"
      oz_image: "$oz_image"
      op_image: "$op_image"
      oc_image: "$oc_image"
      cli_image: "$cli_image"
      release_name: "$release_name"
      helm_debug: "$helm_debug"
      helm_dry_run: "$helm_dry_run"
      landscape: "$landscape"

# Needed to work in Cyfronet
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400